###

GET https://localhost:7254/platos
###

GET https://localhost:7254/platos/9

###

POST https://localhost:7254/platos
Content-Type: application/json

{
  "nombre": "Sanchocho de bufalo 4",
  "precio": 20000,
  "descripcion": "Delicioso sanchocho de bufalo 4",
  "imagen":"/Imagenes/bufalo4.jpg"
}

###
PUT https://localhost:7254/platos/9
Content-Type: application/json

{
  "id": 9,
  "nombre": "Sanchocho de bufalo a la Madrilena delicioso",
  "descripcion": "Delicioso sanchocho de bufalo",
  "precio": 20000.0,
  "imagen": "/Imagenes/bufalo.jpg"
}