// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPICore_RestMaca.Datos;

#nullable disable

namespace WebAPICore_RestMaca.Datos.Migraciones
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("WebAPICore_RestMaca.Entidades.Plato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Delicioso sancocho de gallina con yuca, plátano y mazorca",
                            Imagen = "/Imagenes/chicken.jpg",
                            Nombre = "Sancocho de gallina",
                            Precio = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Delicioso sancocho de pescado con yuca, plátano y mazorca",
                            Imagen = "/Imagenes/fish.jpg",
                            Nombre = "Sancocho de pescado",
                            Precio = 15000m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Delicioso sancocho de res con yuca, plátano y mazorca",
                            Imagen = "/Imagenes/beef.jpg",
                            Nombre = "Sancocho de res",
                            Precio = 15000m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Delicioso sancocho de gallina,pescado y res",
                            Imagen = "/Imagenes/varius.jpg",
                            Nombre = "Sancocho trifasico",
                            Precio = 15000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
